### ISSUE TITLE
Incorrect rss causes failure of newsletter generating process

### ISSUE THREAD

**Issue by tdziurko** [tdziurko/jvm-bloggers#142]
When there is an incorrect or old rss  (e.g. `http://mattagile.com/feeds/posts/default`) there is an exception during newsletter content generation

    Caused by: java.io.FileNotFoundException: http://mattagile.com/feeds/posts/default
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1889) ~[na:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1884) ~[na:1.8.0_51]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1883) ~[na:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1456) ~[na:1.8.0_51]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_51]
	at pl.tomaszdziurko.jvm_bloggers.utils.SyndFeedProducer.createFor(SyndFeedProducer.java:41) ~[main/:na]
	at pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator.getBlogHomepageFromRss(BlogSummaryMailGenerator.java:113) ~[main/:na]
	at pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator.lambda$getBlogAndItsHomepage$12(BlogSummaryMailGenerator.java:108) ~[main/:na]
	at pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator$$Lambda$56/362862376.apply(Unknown Source) ~[na:na]
	at java.util.stream.Collectors.lambda$toMap$172(Collectors.java:1321) ~[na:1.8.0_51]
	at java.util.stream.Collectors$$Lambda$59/2014636288.accept(Unknown Source) ~[na:na]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[na:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[na:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[na:1.8.0_51]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_51]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_51]
	at pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator.getBlogAndItsHomepage(BlogSummaryMailGenerator.java:106) ~[main/:na]
	at pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator.prepareMailContent(BlogSummaryMailGenerator.java:91) ~[main/:na]
	at WICKET_pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator$$FastClassByCGLIB$$c3988fa8.invoke(<generated>) ~[cglib-3.1.jar:na]
	at net.sf.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[cglib-3.1.jar:na]
	at org.apache.wicket.proxy.LazyInitProxyFactory$AbstractCGLibInterceptor.intercept(LazyInitProxyFactory.java:350) ~[wicket-ioc-7.2.0.jar:7.2.0]
	at WICKET_pl.tomaszdziurko.jvm_bloggers.mailing.BlogSummaryMailGenerator$$EnhancerByCGLIB$$68198923.prepareMailContent(<generated>) ~[cglib-3.1.jar:na]
	at pl.tomaszdziurko.jvm_bloggers.view.admin.mailing.MailingTemplatePreviewPanel$1.load(MailingTemplatePreviewPanel.java:36) ~[main/:na]
	at pl.tomaszdziurko.jvm_bloggers.view.admin.mailing.MailingTemplatePreviewPanel$1.load(MailingTemplatePreviewPanel.java:31) ~[main/:na]
	at org.apache.wicket.model.LoadableDetachableModel.getObject(LoadableDetachableModel.java:134) ~[wicket-core-7.2.0.jar:7.2.0]
	at org.apache.wicket.Component.getDefaultModelObject(Component.java:1626) ~[wicket-core-7.2.0.jar:7.2.0]
	... 57 common frames omitted

**Comment by puradawid** [comment]
Does system should inform about such (not existing or temporarily not responding) RSS links?

**Comment by tdziurko** [comment]
First think is that such errors should not prevent template from generating. We use this rss to get blog home page, so if this fetch fails we should display Author name instead of linking to his home page.

**Comment by goostleek** [comment]
Similar situation is handled in [`RssCheckingActor`|https://github.com/tdziurko/jvm-bloggers/blob/85f77d49b33c8d314f278181aa72e9a8f444bb2b/src/main/java/pl/tomaszdziurko/jvm_bloggers/blog_posts/RssCheckingActor.java#L43]. You can do something similar to solve the problem. For sure we want to have some info in logs.

**Comment by tdziurko** [comment]
Anothet idea:
Maybe we could change the way we fetch main page of each blog to have it in our database and fetched/updated when we fetch data from JSON file?
This way newsletter generation process won't be affected by some external events that we don't have control of.

**Comment by delor** [comment]
Maybe we could use a bit more sophisticated http client than `URLConnection`?

**Comment by goostleek** [comment]
Do we need something special from external HTTP client library?

**Comment by delor** [comment]
Better error handling than `FileNotFoundException` would be nice.
`URLConnection` doesn't even implement `java.lang.AutoCloseable`.

**Comment by puradawid** [comment]
Even whether it has to be done, the best place for such improvement is a new issue (as well as @tdziurko improvement suggested above), this scope are just a fixing bug and making system working again.
